name: WallJump
version: '${version}'
main: me.arthed.walljump.WallJump
api-version: '26.2'
softdepend: [WorldGuard, Spartan, AAC, NoCheatPlus, TreysDoubleJump]
authors: [ Arthed ]
description: Adds an easy to understand, yet still challenging wall jump mechanic
commands:
  walljump:
    aliases: [wj, wjump]
